### ISSUE TITLE
Add web3js and get voter wallet to send transactions

### ISSUE THREAD

**Issue by christiankiller** [provotum/frontend#2]
# Description
Load wallet from Identity Provider into frontend in order to send a transaction containing the vote, encrypted with the HE public key from the election (including the NIZKPs).

## Tasks
- [x] Integrate web3js
- [x] Fetch question via geth & Contract address provided by GUI
- [x] Leave out Identity Provider for now: mock by connecting to local geth instance from `eth-private-net`
- [ ] Validate contract input field & omit editing as soon as voting question was fetched. 
- [x] Submit vote via GUI and send to `contractAddress`
- [ ] Add Event Log messages (question fetched, voted, vote in tx in block xxxx) that normally would fire when there was a websocket reply to the REST calls.

## Errors
- [ ] Catch unlock wallet failure e.g. in case the password is wrong
- [ ] Catch errors.js:31 Uncaught Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8502. Uncaught Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8502.

## Acceptance criteria
- [ ] Test transactions using `eth-private-net`can be sucessfully sent via frontend user input.
